################# BASE IMAGE ######################
FROM --platform=linux/amd64 mambaorg/micromamba:1.3.1-focal
# Micromamba for fast building of small conda-based containers.
# https://github.com/mamba-org/micromamba-docker
# The 'base' conda environment is automatically activated when the image is running.

################## METADATA ######################
LABEL base_image="mambaorg/micromamba:1.3.1-focal"
LABEL version="1.0.0"
LABEL software="Subread"
LABEL software.version="2.0.3"
LABEL about.summary="The Subread package comprises a suite of software programs for processing next-gen sequencing read data including Subread, featureCounts, Sublong."
LABEL about.home="https://subread.sourceforge.net/"
LABEL about.documentation="https://subread.sourceforge.net/SubreadUsersGuide.pdf"
LABEL about.license_file=""
LABEL about.license="GPL-3.0-only"

################## MAINTAINER ######################
MAINTAINER Matthew Galbraith <matthew.galbraith@cuanschutz.edu>

################## INSTALLATION ######################

# Copy the yaml file to your docker image and pass it to micromamba
COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes